#!/usr/bin/env python3
"""Reporting and formatting utilities for skill evaluation."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from .evaluate_skill_rubric import SkillReport, get_grade_thresholds, get_weights
from .rubric_enhancements import format_enhancements_report


def format_report_markdown(
    report: SkillReport,
    repo_root: Path,
    config: Dict[str, Any],
    detailed: bool = True,
) -> str:
    weights = get_weights(config)
    thresholds = get_grade_thresholds(config)

    static_score = report.total_weighted(weights)
    display_score = static_score

    lines: List[str] = []
    lines.append(f"## {report.name}\n")
    try:
        path_str = str(report.path.relative_to(repo_root))
    except ValueError:
        path_str = str(report.path)
    lines.append(f"- **路径**: `{path_str}`")
    lines.append(f"- **Skill 类型**: `{report.skill_type}`")
    lines.append(f"- **Rubric 总分**: {static_score:.1f} / 100")
    lines.append(f"- **等级**: {report.grade(display_score, thresholds)}")
    if report.errors:
        lines.append(f"- **评估错误**: {', '.join(report.errors)}")
    lines.append("")

    lines.append("| 维度 | 名称 | 得分 | 证据 | 优化建议 |")
    lines.append("|---|---|---|---|---|")
    for d in report.dimensions:
        evidence = "; ".join(d.evidence) if d.evidence else "-"
        suggestion = "; ".join(d.suggestions) if d.suggestions else "-"
        lines.append(
            f"| {d.code} | {d.name} | {d.score}/{d.max_score} | {evidence} | {suggestion} |"
        )
    lines.append("")

    if report.security_findings:
        lines.append(report.security_findings)
        lines.append("")

    if report.skill_lens_report:
        lines.append(report.skill_lens_report)
        lines.append("")

    if report.runtime_neutrality_report:
        lines.append(report.runtime_neutrality_report)
        lines.append("")

    if report.test_prompts_report:
        lines.append(report.test_prompts_report)
        lines.append("")

    if report.prompts_verification_report:
        lines.append(report.prompts_verification_report)
        lines.append("")

    if report.llm_judgments:
        lines.append("### LLM Judge Contributions")
        for code, judgment in report.llm_judgments.items():
            lines.append(
                f"- **{code}**: scores={judgment.scores}, "
                f"aggregate={judgment.aggregate} → {judgment.aggregated_score}/5"
            )
        lines.append("")

    if report.enhancements:
        lines.append(format_enhancements_report(report.enhancements))
        lines.append("")

    if report.smoke_report:
        lines.append(report.smoke_report)
        lines.append("")

    if report.dependency_report:
        lines.append(report.dependency_report)
        lines.append("")

    if detailed:
        lines.append("### 详细说明\n")
        for d in report.dimensions:
            lines.append(f"**{d.code} {d.name}** — 得分 {d.score}/{d.max_score}")
            if d.evidence:
                lines.append("- 证据：")
                for e in d.evidence:
                    lines.append(f"  - {e}")
            if d.suggestions:
                lines.append("- 建议：")
                for s in d.suggestions:
                    lines.append(f"  - {s}")
            lines.append("")

    return "\n".join(lines)


def format_scorecard(reports: List[SkillReport], config: Dict[str, Any]) -> str:
    weights = get_weights(config)
    thresholds = get_grade_thresholds(config)

    lines: List[str] = []
    lines.append("# Skill Scorecard\n")
    lines.append("Auto-generated by `evaluate_skill_rubric.py`.\n")
    lines.append("| Skill | Type | D1 | D2 | D3 | D4 | D5 | D6 | D7 | D8 | D9 | Score | Grade |")
    lines.append("|---|---|---|---|---|---|---|---|---|---|---|---|---|")
    for r in reports:
        scores = {d.code: d.score for d in r.dimensions}
        cells = [r.name, r.skill_type]
        for code in ["D1", "D2", "D3", "D4", "D5", "D6", "D7", "D8", "D9"]:
            cells.append(str(scores.get(code, "-")))
        static = r.total_weighted(weights)
        cells.append(f"{static:.1f}")
        cells.append(r.grade(static, thresholds))
        lines.append("| " + " | ".join(cells) + " |")
    lines.append("")
    return "\n".join(lines)


def _load_baseline_scores(baseline_path: Path) -> Dict[str, float]:
    """Parse a previous scorecard markdown and return skill -> score."""
    scores: Dict[str, float] = {}
    if not baseline_path.exists():
        return scores

    text = baseline_path.read_text(encoding="utf-8", errors="replace")
    in_table = False
    header_seen = False
    skill_col = score_col = -1

    for line in text.splitlines():
        if line.startswith("| Skill |"):
            in_table = True
            header_seen = True
            cells = [c.strip() for c in line.strip("|").split("|")]
            try:
                skill_col = cells.index("Skill")
                score_col = cells.index("Score")
            except ValueError:
                return scores
            continue

        if in_table and header_seen and line.startswith("|---|"):
            continue

        if in_table and line.startswith("|"):
            cells = [c.strip() for c in line.strip("|").split("|")]
            if len(cells) > max(skill_col, score_col):
                try:
                    scores[cells[skill_col]] = float(cells[score_col])
                except (ValueError, IndexError):
                    pass
    return scores


def write_history(
    reports: List[SkillReport],
    config: Dict[str, Any],
    history_path: Path,
    extra: Optional[Dict[str, Any]] = None,
) -> None:
    """Append evaluation results as JSONL for trend tracking."""
    weights = get_weights(config)
    thresholds = get_grade_thresholds(config)
    now = datetime.now(timezone.utc).isoformat()

    records = []
    for r in reports:
        score = r.total_weighted(weights)
        records.append(
            {
                "timestamp": now,
                "skill": r.name,
                "path": str(r.path),
                "skill_type": r.skill_type,
                "dimensions": {d.code: d.score for d in r.dimensions},
                "score": round(score, 2),
                "grade": r.grade(score, thresholds),
                "errors": r.errors,
                "extra": extra or {},
            }
        )

    history_path.parent.mkdir(parents=True, exist_ok=True)
    with history_path.open("a", encoding="utf-8") as f:
        for rec in records:
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")
